# Generated by Django 6.0 on 2025-12-09 09:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_organization', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asana_workspaces_workspace',
                'indexes': [models.Index(fields=['name'], name='asana_works_name_d3565b_idx'), models.Index(fields=['is_organization'], name='asana_works_is_orga_638b0f_idx')],
            },
        ),
    ]
