# Generated by Django 6.0 on 2025-12-09 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asana_workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asana_users_user',
                'indexes': [models.Index(fields=['email'], name='asana_users_email_d8fc62_idx'), models.Index(fields=['name'], name='asana_users_name_0cc2aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserWorkspaceMembership',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana_users.user')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana_workspaces.workspace')),
            ],
            options={
                'db_table': 'asana_users_userworkspacemembership',
                'unique_together': {('user', 'workspace')},
            },
        ),
    ]
