# Generated by Django 6.0 on 2025-12-09 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asana_users', '0001_initial'),
        ('asana_workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana_workspaces.workspace')),
            ],
            options={
                'db_table': 'asana_teams_team',
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana_teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana_users.user')),
            ],
            options={
                'db_table': 'asana_teams_teammembership',
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['workspace'], name='asana_teams_workspa_df2bea_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='asana_teams_name_d84b79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('team', 'user')},
        ),
    ]
