# Generated by Django 6.0 on 2025-12-09 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asana_tasks', '0001_initial'),
        ('asana_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('html_text', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('comment', 'Comment'), ('system', 'System')], default='comment', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asana_users.user')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana_tasks.task')),
            ],
            options={
                'db_table': 'asana_stories_story',
                'indexes': [models.Index(fields=['task'], name='asana_stori_task_id_adc6d1_idx'), models.Index(fields=['created_by'], name='asana_stori_created_dc307a_idx'), models.Index(fields=['created_at'], name='asana_stori_created_740b1c_idx'), models.Index(fields=['type'], name='asana_stori_type_e64665_idx')],
            },
        ),
    ]
