# Generated by Django 6.0 on 2025-12-09 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asana_tasks', '0001_initial'),
        ('asana_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(default='attachment', max_length=50)),
                ('download_url', models.URLField()),
                ('view_url', models.URLField(blank=True, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asana_users.user')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana_tasks.task')),
            ],
            options={
                'db_table': 'asana_attachments_attachment',
                'indexes': [models.Index(fields=['task'], name='asana_attac_task_id_228dde_idx'), models.Index(fields=['created_by'], name='asana_attac_created_dd60d6_idx'), models.Index(fields=['created_at'], name='asana_attac_created_3b09b7_idx')],
            },
        ),
    ]
