# Generated by Django 6.0 on 2025-12-09 09:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource', models.CharField(max_length=50)),
                ('resource_gid', models.CharField(max_length=36)),
                ('target', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('secret', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asana_webhooks_webhook',
                'indexes': [models.Index(fields=['resource'], name='asana_webho_resourc_50643f_idx'), models.Index(fields=['resource_gid'], name='asana_webho_resourc_87293d_idx'), models.Index(fields=['active'], name='asana_webho_active_1dca88_idx')],
            },
        ),
    ]
