# Generated by Django 6.0 on 2025-12-09 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asana_workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana_workspaces.workspace')),
            ],
            options={
                'db_table': 'asana_tags_tag',
                'indexes': [models.Index(fields=['workspace'], name='asana_tags__workspa_c7bd5e_idx'), models.Index(fields=['name'], name='asana_tags__name_88e98d_idx')],
                'unique_together': {('workspace', 'name')},
            },
        ),
    ]
