# Generated by Django 6.0 on 2025-12-09 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asana_projects', '0001_initial'),
        ('asana_tags', '0001_initial'),
        ('asana_users', '0001_initial'),
        ('asana_workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('assignee_status', models.CharField(choices=[('upcoming', 'Upcoming'), ('later', 'Later'), ('new', 'New'), ('inbox', 'Inbox'), ('today', 'Today')], default='inbox', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('start_on', models.DateField(blank=True, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('html_notes', models.TextField(blank=True, null=True)),
                ('num_hearts', models.IntegerField(default=0)),
                ('num_likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asana_users.user')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='asana_users.user')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana_workspaces.workspace')),
            ],
            options={
                'db_table': 'asana_tasks_task',
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='asana_tasks.task')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='asana_tasks.task')),
            ],
            options={
                'db_table': 'asana_tasks_taskdependency',
            },
        ),
        migrations.CreateModel(
            name='TaskFollower',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana_tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana_users.user')),
            ],
            options={
                'db_table': 'asana_tasks_taskfollower',
            },
        ),
        migrations.CreateModel(
            name='TaskProject',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana_projects.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana_tasks.task')),
            ],
            options={
                'db_table': 'asana_tasks_taskproject',
            },
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana_tags.tag')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana_tasks.task')),
            ],
            options={
                'db_table': 'asana_tasks_tasktag',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace'], name='asana_tasks_workspa_ce1f91_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee'], name='asana_tasks_assigne_c1b2d5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['completed'], name='asana_tasks_complet_558df1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_on'], name='asana_tasks_due_on_018a44_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_at'], name='asana_tasks_due_at_76b621_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by'], name='asana_tasks_created_911312_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('predecessor', 'successor')},
        ),
        migrations.AlterUniqueTogether(
            name='taskfollower',
            unique_together={('task', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='taskproject',
            unique_together={('task', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='tasktag',
            unique_together={('task', 'tag')},
        ),
    ]
