# Generated by Django 6.0 on 2025-12-09 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asana_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='num_subtasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='asana_tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='resource_subtype',
            field=models.CharField(choices=[('default_task', 'Default Task'), ('milestone', 'Milestone'), ('approval', 'Approval')], default='default_task', max_length=20),
        ),
    ]
