# Generated by Django 6.0 on 2025-12-09 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asana_teams', '0001_initial'),
        ('asana_users', '0001_initial'),
        ('asana_workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('public', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('start_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asana_users.user')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asana_teams.team')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana_workspaces.workspace')),
            ],
            options={
                'db_table': 'asana_projects_project',
                'indexes': [models.Index(fields=['workspace'], name='asana_proje_workspa_c1a8ff_idx'), models.Index(fields=['team'], name='asana_proje_team_id_3dc7b1_idx'), models.Index(fields=['archived'], name='asana_proje_archive_760910_idx'), models.Index(fields=['public'], name='asana_proje_public_c16a4e_idx'), models.Index(fields=['created_by'], name='asana_proje_created_a815ed_idx')],
            },
        ),
    ]
