# Generated by Django 6.0 on 2025-12-09 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asana_projects', '0001_initial'),
        ('asana_teams', '0001_initial'),
        ('asana_users', '0001_initial'),
        ('asana_workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFollower',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asana_projects_project_follower',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('commenter', 'Commenter'), ('viewer', 'Viewer')], default='editor', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asana_projects_project_member',
            },
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='asana_proje_created_a815ed_idx',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='due_date',
            new_name='due_on',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_projects', to='asana_users.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='default_view',
            field=models.CharField(choices=[('list', 'List'), ('board', 'Board'), ('calendar', 'Calendar'), ('timeline', 'Timeline')], default='list', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='html_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, choices=[('list', 'list'), ('board', 'board'), ('timeline', 'timeline'), ('calendar', 'calendar'), ('rocket', 'rocket'), ('people', 'people'), ('graph', 'graph'), ('star', 'star'), ('bug', 'bug'), ('light_bulb', 'light_bulb'), ('globe', 'globe'), ('gear', 'gear'), ('notebook', 'notebook'), ('computer', 'computer'), ('check', 'check'), ('target', 'target'), ('html', 'html'), ('megaphone', 'megaphone'), ('chat_bubbles', 'chat_bubbles'), ('briefcase', 'briefcase'), ('page_layout', 'page_layout'), ('mountain_flag', 'mountain_flag'), ('puzzle', 'puzzle'), ('presentation', 'presentation'), ('line_and_symbols', 'line_and_symbols'), ('speed_dial', 'speed_dial'), ('ribbon', 'ribbon'), ('shoe', 'shoe'), ('shopping_basket', 'shopping_basket'), ('map', 'map'), ('ticket', 'ticket'), ('coins', 'coins')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to='asana_users.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, choices=[('dark-pink', 'Dark Pink'), ('dark-green', 'Dark Green'), ('dark-blue', 'Dark Blue'), ('dark-red', 'Dark Red'), ('dark-teal', 'Dark Teal'), ('dark-brown', 'Dark Brown'), ('dark-orange', 'Dark Orange'), ('dark-purple', 'Dark Purple'), ('dark-warm-gray', 'Dark Warm Gray'), ('light-pink', 'Light Pink'), ('light-green', 'Light Green'), ('light-blue', 'Light Blue'), ('light-red', 'Light Red'), ('light-teal', 'Light Teal'), ('light-brown', 'Light Brown'), ('light-orange', 'Light Orange'), ('light-purple', 'Light Purple'), ('light-warm-gray', 'Light Warm Gray'), ('none', 'None')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to='asana_users.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='asana_teams.team'),
        ),
        migrations.AlterField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='asana_workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['completed'], name='asana_proje_complet_560e51_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='asana_proje_owner_i_917e8c_idx'),
        ),
        migrations.AddField(
            model_name='projectfollower',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='asana_projects.project'),
        ),
        migrations.AddField(
            model_name='projectfollower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_projects', to='asana_users.user'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='asana_projects.project'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='asana_users.user'),
        ),
        migrations.AlterUniqueTogether(
            name='projectfollower',
            unique_together={('project', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'user')},
        ),
    ]
